version: 3
metadata_directory: metadata

env:
  HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
  HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
  HASURA_GRAPHQL_ADMIN_SECRET: youradminsecret

# Additional configuration options...

actions:
    kind: synchronous
    handler_webhook_baseurl: http://localhost:3000
